#!/bin/bash

echo "Enter your AD password:"
stty_orig=`stty -g`
stty -echo
read PASS
stty $stty_orig

output_dir=../configs/SRX
list=listSRX
devices=`cat $list`
template=SRX-expect

for device in $devices
do

chmod +x $template
./$template $device $PASS | tee $output_dir/tmp/$device.tmp

grep KNOWN $output_dir/tmp/$device.tmp
a=$?

grep TIMED $output_dir/tmp/$device.tmp
b=$?

if [ "$a" -eq 0 ];then
echo "" >> $output_dir/UNKNOWN-$device

else if [ "$b" -eq 0 ];then
echo "" >> $output_dir/TIMEOUT-$device

#else

#grep snmp-server $output_dir/tmp/$device.tmp | grep -v $device > $output_dir/$platform-$device
#echo "" >> $output_dir/$platform-$device

fi
fi

done
